// CONFIG
export const SUGGESTIONS_TUNNEL = 'http';

// ACTION TYPES
export const CHANGE_URL = 'CHANGE_URL';
export const LOAD_TOKEN = 'LOAD_TOKEN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REFRESH_ROOMS_LIST = 'REFRESH_ROOMS_LIST';
export const SELECT_ROOM = 'SELECT_ROOM';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const HANDLE_MESSAGE = 'HANDLE_MESSAGE';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const UPDATE_ROOM_HISTORY = 'UPDATE_ROOM_HISTORY';
export const TEAM_INFO_PAGE = 'TEAM_INFO_PAGE';
export const PLAYER_INFO_PAGE = 'PLAYER_INFO_PAGE';

export const LOADING_INFO_PAGE = 'LOADING_INFO_PAGE';
export const INFO_PAGE = 'INFO_PAGE';

export const LOAD_LIVE_PROMPT_WINDOW = 'LOAD_LIVE_PROMPT_WINDOW';
export const FIND_SUGESTIONS = 'FIND_SUGESTIONS';
export const LOADING_PROP_SUGGESTIONS = 'LOADING_PROP_SUGGESTIONS';
export const LOADED_PROP_SUGGESTIONS = 'LOADED_PROP_SUGGESTIONS';
export const LOADING_SERVER_HEALTH = 'LOADING_SERVER_HEALTH';
export const LOADED_SERVER_HEALTH = 'LOADED_SERVER_HEALTH';

export const SHOW_INFO_DATA_PANEL = 'SHOW_INFO_DATA_PANEL';
export const LOADING_INFO_DATA_ACTION = 'LOADING_INFO_DATA_ACTION';
export const LOADED_INFO_DATA_ACTION = 'LOADED_INFO_DATA_ACTION';

export const LOAD_BET_BROWSER_WINDOW = 'LOAD_BET_BROWSER_WINDOW';
export const LOADED_BET_BROWSER = 'LOADED_BET_BROWSER';
export const LOADING_BET_BROWSER = 'LOADING_BET_BROWSER';

export const TOGGLE_APP_STATE = 'TOGGLE_APP_STATE';
// export const HIDE_APP_STATE = 'HIDE_APP_STATE';
